version: "3.8"

services:
  canvas-collab-server:
    image: orangery/canvas-collab-server:latest
    container_name: ${APP_NAME:-canvas-collab}-server
    restart: unless-stopped

    ports:
      - "1234:1234"
    env_file:
      - .env
